services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_NAME=${APP_NAME:-Modulo CMS}
      - DB_CONNECTION=${DB_CONNECTION:-sqlite}
      - DB_DATABASE=/var/www/database/database.sqlite
      - DEFAULT_THEME=${DEFAULT_THEME:-modern-react}
      - SEED_EXAMPLE_CONTENT=${SEED_EXAMPLE_CONTENT:-true}
    command: >
      sh -c "
        cd /var/www &&
        composer install --optimize-autoloader --ignore-platform-req=php &&
        mkdir -p storage/framework/{sessions,views,cache} bootstrap/cache database &&
        chmod -R 777 storage bootstrap/cache database &&
        if [ ! -f .env ]; then
          if [ -f .env.docker ]; then
            cp .env.docker .env
          elif [ -f .env.example ]; then
            cp .env.example .env
          else
            echo 'APP_NAME=\"Modulo CMS\"' > .env
            echo 'APP_ENV=local' >> .env
            echo 'APP_KEY=' >> .env
            echo 'APP_DEBUG=true' >> .env
            echo 'DB_CONNECTION=sqlite' >> .env
            echo 'DB_DATABASE=/var/www/database/database.sqlite' >> .env
          fi
        fi &&
        [ ! -f database/database.sqlite ] && touch database/database.sqlite || true &&
        chmod 666 database/database.sqlite &&
        php artisan key:generate --force &&
        php artisan migrate --force &&
        php artisan serve --host=0.0.0.0 --port=8080
      "

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: >
      sh -c "
        bun install &&
        bun run build &&
        bunx vite --host=0.0.0.0
      "
    depends_on:
      - backend
